name: EESSI run

on:
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: eessi/github-action-eessi@v3
    - uses: actions/checkout@v4

    - name: Build fiat
      run: |
        module load EESSI-extend
        eb --robot ${{github.workspace}}/fiat-1.6.1-GCC-13.2.0.eb

    - name: Load environment
      run: |
        module load CMake/3.27.6-GCCcore-13.2.0
        module load ecBuild/3.8.0
        module load gompi/2023b
        module load FFTW/3.3.10-GCC-13.2.0
        module load ScaLAPACK/2.2.0-gompi-2023b-fb 
        module load EESSI-extend
        module load fiat/1.6.1-GCC-13.2.0
        
        module list

    - name: Configure ectrans
      run: cmake -B ${{github.workspace}}/build 

    - name: Build ectrans
      run: cmake --build ${{github.workspace}}/build 

    - name: Run tests
      working-directory: ${{github.workspace}}/build

      run: ctest
